---
title: "Simple document"
output: github_document
---
```{r}
library(tidyverse)
library(readxl)
library(haven)
```


let's import the `FAS_litters.csv` csv.

```{r}
litters_df = 
    read_csv("data/FAS_litters.csv")

litters_df = 
  janitor::clean_names(litters_df)

```

import the `FAS_pups`.
```{r}
pups_df = 
    read_csv("data/FAS_pups.csv")

pups_df = 
  janitor::clean_names(pups_df)
```



##look at data
```{r}
litters_df

head(litters_df)

tail(litters_df)
```


you can use view
```{r, eval = FALSE}
view(litters_df)
```

LOOK at a data summary
```{r}
str(litters_df)

skimr::skim(litters_df)
```


##Options in `read_*`

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    skip = 10, col_names = FALSE)
```

look at NA values
```{r}
litters_df = 
   read_csv(
     "data/FAS_litters.csv",
     na = c("NA", 19, "."))
```

COLUMN TYPES
```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    col_types = 
      cols(
        `GD0 weight` = col_factor()
      ))
```



## Other file types

Import excel file

```{r}
mlb_df = 
  read_excel("data/mlb11.xlsx")
```


SAS file
```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat")
```







